language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/
before_install:
  - chmod +x gradlew
install: skip

script:
  - ./gradlew tasks
  - ./gradlew build

notifications:
  email:
    on_success: never
    on_failure: always
